export default [
  {
    type: "categ",
    label: "Interface",
    children: [
      {
        type: "select",
        icon: "palette-filled",
        label: "Thème",
        description: "Défini le thème de l'application",
        options: [
          { label: "Sombre", value: "dark" },
          { label: "Clair", value: "light" },
          { label: "Système", value: "system" },
        ],
        storePath: ["settings", "theme"],
      },
      {
        type: "select",
        icon: "metronome",
        label: "Fréquence de rafraichissement",
        description: "Défini la fréquence de rafraichissement des données",
        options: [
          { label: "500ms", value: 500 },
          { label: "1s", value: 1000 },
          { label: "2s", value: 2000 },
          { label: "3s", value: 3000 },
          { label: "4s", value: 4000 },
          { label: "5s", value: 5000 },
          { label: "10s", value: 10000 },
          { label: "20s", value: 20000 },
          { label: "30s", value: 30000 },
          { label: "1min", value: 60000 },
        ],
        storePath: ["settings", "nodeFrequency"],
      },
      {
        type: "number",
        icon: "table-filled",
        label: "Nombre de colonnes",
        description: "Défini le nombre de colonnes pour l'affichage des graphiques",
        storePath: ["settings", "chartColumns"],
      },
      {
        type: "number",
        icon: "table-filled",
        label: "Hauteur des graphiques",
        description: "Défini la hauteur des graphiques affichés",
        min: 5,
        max: 50,
        storePath: ["settings", "chartHeight"],
      },
      {
        type: "number",
        icon: "arrow-autofit-width-filled",
        label: "Taille du buffer",
        description: "Défini le temps en minute des données à conserver dans les graphiques",
        max: 30,
        storePath: ["settings", "chartBufferSize"],
      },
      {
        type: "switch",
        icon: "player-play-filled",
        label: "Animation des graphiques",
        description: "Active ou désactive les animations lors de l'actualisation des graphiques",
        info: "L'activation des animations peut augmenter significativement la charge processeur, particulièrement avec un grand nombre de graphiques affichés simultanément.",
        storePath: ["settings", "chartAnimation"],
      },
      {
        type: "switch",
        icon: "chart-area-filled",
        label: "Heures des graphiques",
        description: "Affiche sur l'axe des abscisses l'heure de la donnée",
        storePath: ["settings", "showXLabel"],
      },
      {
        type: "switch",
        icon: "heading",
        label: "Titres des graphiques",
        description: "Affiche le titre des graphiques",
        storePath: ["settings", "showChartTitle"],
      },
      {
        type: "switch",
        icon: "layout-sidebar-left-collapse-filled",
        label: "Menu latéral",
        description: "Affiche le menu de l'application sur le côté gauche",
        storePath: ["settings", "showSideMenu"],
      },
    ],
  },
  {
    type: "categ",
    label: "Système",
    children: [
      {
        type: "switch",
        icon: "power",
        label: "Lancer au démarrage",
        description: "Lance l'application au démarrage de l'ordinateur",
        storePath: ["electron", "startOnLogin"],
      },
      {
        type: "switch",
        icon: "minimize",
        label: "Ouvrir minimisé",
        description: "Ouvre l'application seulement dans la barre des tâches",
        storePath: ["electron", "startMinimized"],
      },
    ],
  },
  {
    type: "categ",
    label: "Mise à jour",
    children: [
      {
        type: "switch",
        icon: "refresh",
        label: "Mise à jour automatique",
        description: "Vérifie si une mise à jour est disponible au démarrage de l'application",
        storePath: ["settings", "autoUpdate"],
      },
      {
        type: "select",
        icon: "git-branch",
        label: "Canal de mise à jour",
        description:
          "Vérifiera et installera automatiquement la dernière version du canal sélectionné",
        options: [
          { label: "Live", value: "latest" },
          { label: "Preview", value: "beta" },
          { label: "Nightly", value: "alpha" },
        ],
        storePath: ["settings", "updateChanel"],
      },
    ],
  },
];
