import { computed, ref } from "vue";

export function useEchartTheme(theme) {
  const modalColor = computed(() => theme?.common?.modalColor);
  const primaryColor = computed(() => theme?.common?.primaryColor);
  const textColor = computed(() => theme?.common?.textColorBase);
  const borderColor = computed(() => theme?.common?.borderColor);

  return ref({
    backgroundColor: "transparent",
    titleColor: textColor.value,
    subtitleColor: textColor.value,
    textColorShow: false,
    textColor: textColor.value,
    markTextColor: textColor.value,
    color: [primaryColor.value, "#63e2b7", "#759aa0", "#e69d87", "#8dc1a9"],
    borderColor: borderColor.value,
    borderWidth: 0,
    visualMapColor: ["#bf444c", "#d88273", "#f6efa6"],
    legendTextColor: textColor.value,
    kColor: "#fd1050",
    kColor0: "#0cf49b",
    kBorderColor: "#fd1050",
    kBorderColor0: "#0cf49b",
    kBorderWidth: 1,
    lineWidth: 2,
    symbolSize: 4,
    symbol: "circle",
    symbolBorderWidth: 1,
    lineSmooth: false,
    graphLineWidth: 1,
    graphLineColor: borderColor.value,
    mapLabelColor: "#000",
    mapLabelColorE: "rgb(100,0,0)",
    mapBorderColor: "#444",
    mapBorderColorE: "#444",
    mapBorderWidth: 0.5,
    mapBorderWidthE: 1,
    mapAreaColor: textColor.value,
    mapAreaColorE: "rgba(255,215,0,0.8)",
    axes: [
      {
        type: "all",
        name: "Axes universels",
        axisLineShow: true,
        axisLineColor: "#333",
        axisTickShow: true,
        axisTickColor: "#333",
        axisLabelShow: true,
        axisLabelColor: "#333",
        splitLineShow: true,
        splitLineColor: [borderColor.value],
        splitAreaShow: false,
        splitAreaColor: [textColor.value],
      },
      {
        type: "category",
        name: "Catégorie Axe",
        axisLineShow: true,
        axisLineColor: "#333",
        axisTickShow: true,
        axisTickColor: "#333",
        axisLabelShow: true,
        axisLabelColor: "#333",
        splitLineShow: false,
        splitLineColor: [borderColor.value],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.3)", "rgba(200,200,200,0.3)"],
      },
      {
        type: "value",
        name: "Axes numériques",
        axisLineShow: true,
        axisLineColor: "#333",
        axisTickShow: true,
        axisTickColor: "#333",
        axisLabelShow: true,
        axisLabelColor: "#333",
        splitLineShow: true,
        splitLineColor: [borderColor.value],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.3)", "rgba(200,200,200,0.3)"],
      },
      {
        type: "log",
        name: "Axes logarithmiques",
        axisLineShow: true,
        axisLineColor: "#333",
        axisTickShow: true,
        axisTickColor: "#333",
        axisLabelShow: true,
        axisLabelColor: "#333",
        splitLineShow: true,
        splitLineColor: [borderColor.value],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.3)", "rgba(200,200,200,0.3)"],
      },
      {
        type: "time",
        name: "Axes temporels",
        axisLineShow: true,
        axisLineColor: "#333",
        axisTickShow: true,
        axisTickColor: "#333",
        axisLabelShow: true,
        axisLabelColor: "#333",
        splitLineShow: true,
        splitLineColor: [borderColor.value],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.3)", "rgba(200,200,200,0.3)"],
      },
    ],
    axisSeperateSetting: false,
    toolboxColor: "#999",
    toolboxEmphasisColor: "#666",
    tooltip: {
      backgroundColor: modalColor.value,
      borderColor: borderColor.value,
      textStyle: {
        color: textColor.value,
      },
    },
    tooltipAxisColor: textColor.value,
    tooltipAxisWidth: 1,
    timelineLineColor: "00FF80",
    timelineLineWidth: 1,
    timelineItemColor: "#00FF80",
    timelineItemColorE: "#a9334c",
    timelineCheckColor: "#e43c59",
    timelineCheckBorderColor: "rgba(194,53,49, 0.5)",
    timelineItemBorderWidth: 1,
    timelineControlColor: "00FF80",
    timelineControlBorderColor: "00FF80",
    timelineControlBorderWidth: 0.5,
    timelineLabelColor: "00FF80",
    datazoomBackgroundColor: "rgba(47,69,84,0)",
    datazoomDataColor: "rgba(255,255,255,0.3)",
    datazoomFillColor: "rgba(167,183,204,0.4)",
    datazoomHandleColor: "#a7b7cc",
    datazoomHandleWidth: "100",
    datazoomLabelColor: textColor.value,
  });
}
