name: Build & Release

on:
  push:
    branches:
      - main
      - develop

env:
  NODE_VERSION: '22'

jobs:
  prepare_build:
    name: Préparer les variables de build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-vars.outputs.version }}
      appname: ${{ steps.set-vars.outputs.appname }}
      yml: ${{ steps.set-vars.outputs.yml }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Calcul des variables
        id: set-vars
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          APPNAME=$(node -e "console.log(require('./package.json').name)")
          YML=latest

          if [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            VERSION="$VERSION-beta"
            APPNAME="$APPNAME-beta"
            YML=beta
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "appname=$APPNAME" >> $GITHUB_OUTPUT
          echo "yml=$YML" >> $GITHUB_OUTPUT

  build_binaries:
    name: Build ${{ matrix.target }}
    needs: prepare_build
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.prepare_build.outputs.version }}
    strategy:
      matrix:
        target: [ win, linux ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Afficher la version
        run: echo "Package version $VERSION"

      - name: Mettre à jour la version package.json
        run: npm version "$VERSION" --no-git-tag-version

      - name: Installer les dépendances
        run: npm install

      - name: Build ${{ matrix.target }}
        run: npm run build:${{ matrix.target }}

      - name: Upload artefact ${{ matrix.target }}
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.target }}
          path: dist/*.*

  upload_and_release:
    name: Upload vers GitHub Release
    runs-on: ubuntu-latest
    needs: [prepare_build, build_binaries]
    if: github.ref_name == 'main' || github.ref_name == 'develop'
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-win
          path: dist

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-linux
          path: dist

      - name: Defining file variables
        id: set-filenames
        run: |
          BINARY_WIN="${{ github.event.repository.name }}-${{ needs.prepare_build.outputs.version }}-setup.exe"
          BINARY_LINUX="${{ github.event.repository.name }}-${{ needs.prepare_build.outputs.version }}.AppImage"
          BINARY_DEB="${{ github.event.repository.name }}-${{ needs.prepare_build.outputs.version }}-amd64.deb"
          BINARY_SNAP="${{ github.event.repository.name }}-${{ needs.prepare_build.outputs.version }}-amd64.snap"
          YML_WIN="${{ needs.prepare_build.outputs.yml }}.yml"
          YML_LINUX="${{ needs.prepare_build.outputs.yml }}-linux.yml"
          echo "binary_win=$BINARY_WIN" >> $GITHUB_OUTPUT
          echo "binary_linux=$BINARY_LINUX" >> $GITHUB_OUTPUT
          echo "binary_deb=$BINARY_DEB" >> $GITHUB_OUTPUT
          echo "binary_snap=$BINARY_SNAP" >> $GITHUB_OUTPUT
          echo "yml_win=$YML_WIN" >> $GITHUB_OUTPUT
          echo "yml_linux=$YML_LINUX" >> $GITHUB_OUTPUT

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare_build.outputs.version }}
          name: v${{ needs.prepare_build.outputs.version }}
          body: "Release automatique générée par GitHub Actions"
          files: |
            dist/${{ steps.set-filenames.outputs.binary_win }}
            dist/${{ steps.set-filenames.outputs.binary_linux }}
            dist/${{ steps.set-filenames.outputs.binary_deb }}
            dist/${{ steps.set-filenames.outputs.binary_snap }}
            dist/${{ steps.set-filenames.outputs.yml_win }}
            dist/${{ steps.set-filenames.outputs.yml_linux }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
